# Generated by Django 2.1.7 on 2019-03-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functioncodemodel',
            name='parent',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='functioncodemodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
