# Generated by Django 2.1.7 on 2019-03-30 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionCodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starting', models.BooleanField()),
                ('code', models.TextField()),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('user_address', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.TextField(max_length=255)),
                ('eth_amount', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='functioncodemodel',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.FunctionModel'),
        ),
    ]
